In [1]:
!date
import pandas as pd
import numpy as np
import sys
sys.path.append('../dev')

import utils
import enrich

pd.options.display.max_colwidth = 100
import os

Mon Jul  8 09:54:21 HST 2024

Input: kegg orthologs
Maps to: reactions
enriches: reactions against pathways

display_input = True -> instead of displaying the reactions found in the pathways, displays the kegg orthologs instead
note: display_gene_symbol doesn't do anything for kegg. With gocams, it is the default, and sets the gene symbol to be displayed instead of uniprot IDs, which are the backend data type in reactome.

In [2]:
kegg = enrich.enrich_wrapper('kegg_test_ko.csv','ko',method='set',fpath = '../test_data/processed/', kegg = True, display_input = True,return_all = True)

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways. Other mappings/enrichments and custom addition or removal of entities not implemented yet

100%|████████████████████████████████████████| 48/48 [00:00<00:00, 11753.55it/s]

Analysis run on 79 entities from 27 out of 28 input genes

In [3]:
kegg[5]

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,Glycolysis / Gluconeogenesis,9.320789e-19,18,53,"[K00001, K00002, K00016, K00114, K00128, K00131, K00134, K00138, K00150, K00161, K00161, K00169,...",ko00010
1,Pyruvate metabolism,1.703289e-10,13,65,"[K00001, K00002, K00016, K00114, K00128, K00138, K00161, K00161, K00169, K00382, K00627, K00873,...",ko00620
2,Chloroalkane and chloroalkene degradation,6.229512e-06,6,25,"[K00001, K00001, K00114, K00128, K00128, K00128]",ko00625
3,Citrate cycle (TCA cycle),1.264370e-05,6,28,"[K00161, K00161, K00169, K00174, K00382, K00627]",ko00020
4,Carbon metabolism,1.224404e-04,13,202,"[K00121, K00131, K00134, K00150, K00161, K00169, K00174, K00382, K00382, K00844, K00850, K00850,...",ko01200
5,Drug metabolism - cytochrome P450,3.802876e-04,3,8,"[K00001, K00001, K00001]",ko00982
6,"Valine, leucine and isoleucine degradation",1.533085e-03,5,44,"[K00128, K00189, K00189, K00189, K00382]",ko00280
7,Galactose metabolism,2.273745e-03,5,48,"[K00844, K00850, K00850, K00850, K00850]",ko00052

Input: kegg orthologs
Maps to: reactions
enriches: reactions against pathways

default: displays the reactions found in the pathways

In [4]:
kegg = enrich.enrich_wrapper('kegg_test_ko.csv','ko',method='set',fpath = '../test_data/processed/', kegg = True, display_input = False,return_all = True)

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways. Other mappings/enrichments and custom addition or removal of entities not implemented yet

100%|████████████████████████████████████████| 48/48 [00:00<00:00, 14623.85it/s]

Analysis run on 79 entities from 27 out of 28 input genes

In [5]:
kegg[5]

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,Glycolysis / Gluconeogenesis,9.320789e-19,18,53,"[R00754, R00746, R00703, R05198, R00710, R01058, R01061, R00711, R01063, R00014, R03270, R01196,...",ko00010
1,Pyruvate metabolism,1.703289e-10,13,65,"[R00754, R00746, R00703, R05198, R00710, R00711, R00014, R03270, R01196, R07618, R02569, R00200,...",ko00620
2,Chloroalkane and chloroalkene degradation,6.229512e-06,6,25,"[R05233, R05234, R05285, R05237, R05238, R05286]",ko00625
3,Citrate cycle (TCA cycle),1.264370e-05,6,28,"[R00014, R03270, R01196, R01197, R07618, R02569]",ko00020
4,Carbon metabolism,1.224404e-04,13,202,"[R06983, R01058, R01061, R01063, R00209, R01196, R01197, R01221, R08549, R01786, R00756, R04779,...",ko01200
5,Drug metabolism - cytochrome P450,3.802876e-04,3,8,"[R08281, R08306, R08310]",ko00982
6,"Valine, leucine and isoleucine degradation",1.533085e-03,5,44,"[R03869, R07160, R08566, R08567, R07618]",ko00280
7,Galactose metabolism,2.273745e-03,5,48,"[R01786, R03236, R03237, R03238, R03239]",ko00052

Input: EC numbers (second argument should be 'enzyme')
Maps to: reactions
enriches: reactions against pathways

default: displays the reactions found in the pathways

In [6]:
kegg = enrich.enrich_wrapper('kegg_test_ec.csv','enzyme',method='set',fpath = '../test_data/processed/', kegg = True, return_all = True)

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways. Other mappings/enrichments and custom addition or removal of entities not implemented yet

100%|████████████████████████████████████████| 27/27 [00:00<00:00, 16072.41it/s]

Analysis run on 41 entities from 13 out of 14 input genes

In [7]:
kegg[5]

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,Glycolysis / Gluconeogenesis,5.630106e-21,16,53,"[R00959, R02738, R01600, R01786, R02187, R02189, R09085, R09086, R02739, R02740, R03321, R04780,...",ko00010
1,Pentose phosphate pathway,7.306845e-07,7,53,"[R01057, R02739, R02740, R04780, R04779, R09084, R02073]",ko00030
2,Microbial metabolism in diverse environments,5.967443e-06,23,942,"[R00959, R01600, R01786, R02187, R02189, R09085, R09086, R02739, R02740, R03321, R00762, R01845,...",ko01120
3,Galactose metabolism,6.863091e-06,6,48,"[R00959, R01786, R03236, R03237, R03238, R03239]",ko00052
4,Carbon metabolism,2.329022e-05,10,202,"[R01786, R02189, R09085, R02740, R00762, R01845, R04780, R00756, R04779, R09084]",ko01200
5,Amino sugar and nucleotide sugar metabolism,2.802148e-05,8,125,"[R00959, R02738, R01326, R01786, R01961, R03920, R02189, R02740]",ko00520
6,Fructose and mannose metabolism,4.841043e-04,5,66,"[R00867, R01326, R04780, R04779, R02073]",ko00051
7,Biosynthesis of nucleotide sugars,1.675469e-03,7,175,"[R00959, R01326, R01786, R01961, R03920, R02189, R02740]",ko01250

Input: EC
Maps to: reactions
enriches: reactions against pathways

display_input = True -> instead of displaying the reactions found in the pathways, displays the ECs instead

In [8]:
kegg = enrich.enrich_wrapper('kegg_test_ec.csv','enzyme',method='set',fpath = '../test_data/processed/', kegg = True, display_input = True, return_all = True)

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways. Other mappings/enrichments and custom addition or removal of entities not implemented yet

100%|████████████████████████████████████████| 27/27 [00:00<00:00, 14885.15it/s]

Analysis run on 41 entities from 13 out of 14 input genes

In [9]:
kegg[5]

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,Glycolysis / Gluconeogenesis,5.630106e-21,16,53,"[5.4.2.2, 2.7.1.199, 2.7.1.1, 2.7.1.1, 2.7.1.63, 2.7.1.63, 2.7.1.147, 2.7.1.147, 5.3.1.9, 5.3.1....",ko00010
1,Pentose phosphate pathway,7.306845e-07,7,53,"[5.4.2.2, 5.3.1.9, 5.3.1.9, 3.1.3.11, 2.7.1.11, 2.7.1.146, 2.7.1.90]",ko00030
2,Microbial metabolism in diverse environments,5.967443e-06,23,942,"[5.4.2.2, 2.7.1.1, 2.7.1.1, 2.7.1.63, 2.7.1.63, 2.7.1.147, 2.7.1.147, 5.3.1.9, 5.3.1.9, 5.3.1.9,...",ko01120
3,Galactose metabolism,6.863091e-06,6,48,"[5.4.2.2, 2.7.1.1, 2.7.1.11, 2.7.1.11, 2.7.1.11, 2.7.1.11]",ko00052
4,Carbon metabolism,2.329022e-05,10,202,"[2.7.1.1, 2.7.1.63, 2.7.1.147, 5.3.1.9, 3.1.3.11, 3.1.3.11, 3.1.3.11, 2.7.1.11, 2.7.1.11, 2.7.1....",ko01200
5,Amino sugar and nucleotide sugar metabolism,2.802148e-05,8,125,"[5.4.2.2, 2.7.1.199, 2.7.1.1, 2.7.1.1, 2.7.1.1, 2.7.1.1, 2.7.1.63, 5.3.1.9]",ko00520
6,Fructose and mannose metabolism,4.841043e-04,5,66,"[2.7.1.1, 2.7.1.1, 3.1.3.11, 2.7.1.11, 2.7.1.90]",ko00051
7,Biosynthesis of nucleotide sugars,1.675469e-03,7,175,"[5.4.2.2, 2.7.1.1, 2.7.1.1, 2.7.1.1, 2.7.1.1, 2.7.1.63, 5.3.1.9]",ko01250