In [1]:
!date
import pandas as pd
import numpy as np
import sys
sys.path.append('../dev')

import utils
import enrich

pd.options.display.max_colwidth = 100
import os

Mon Jul 15 15:39:48 PDT 2024

Input: kegg orthologs

Maps to: reactions

enriches: reactions against pathways

display_input = True -> instead of displaying the reactions found in the pathways, displays the kegg orthologs instead

note: display_gene_symbol doesn't do anything for kegg. With gocams, it is the default, and sets the gene symbol to be displayed instead of uniprot IDs, which are the backend data type in reactome.

In [3]:
enrich.enrich_wrapper('kegg_test_ko.csv','ko',method='set',fpath = '../test_data/processed/', kegg = True, display_input = True,  enrich_against = 'pathway')

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways or modules. Reactions are treated as "sets." Custom addition or removal of entities not implemented yet. Weighted enrichment against pathways is slow due to large sizes; enrich_against for this is set to "module" as default. Certain non-meaningful pathways such as k01100 "Metabolic Pathways" are removed from enrichment.

100%|█████████████████████████████████████████████████| 48/48 [00:00<00:00, 8111.79it/s]

Analysis run on 79 entities from 27 out of 28 input genes

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,Glycolysis / Gluconeogenesis,9.320789e-19,18,53,"[K00001, K00002, K00016, K00114, K00128, K00131, K00134, K00138, K00150, K00161, K00161, K00169,...",ko00010
1,Pyruvate metabolism,1.703289e-10,13,65,"[K00001, K00002, K00016, K00114, K00128, K00138, K00161, K00161, K00169, K00382, K00627, K00873,...",ko00620
2,Chloroalkane and chloroalkene degradation,6.229512e-06,6,25,"[K00001, K00001, K00114, K00128, K00128, K00128]",ko00625
3,Citrate cycle (TCA cycle),1.264370e-05,6,28,"[K00161, K00161, K00169, K00174, K00382, K00627]",ko00020
4,Carbon metabolism,1.224404e-04,13,202,"[K00121, K00131, K00134, K00150, K00161, K00169, K00174, K00382, K00382, K00844, K00850, K00850,...",ko01200
5,Drug metabolism - cytochrome P450,3.802876e-04,3,8,"[K00001, K00001, K00001]",ko00982
6,"Valine, leucine and isoleucine degradation",1.533085e-03,5,44,"[K00128, K00189, K00189, K00189, K00382]",ko00280
7,Galactose metabolism,2.273745e-03,5,48,"[K00844, K00850, K00850, K00850, K00850]",ko00052

**Weighted Enrichment**

Input: kegg orthologs

Maps to: reactions

enriches: reactions against modules


default: displays the reactions found in the pathways

In [4]:
enrich.enrich_wrapper('kegg_test_ko.csv','ko',method='ncHGT',fpath = '../test_data/processed/', kegg = True, display_input = True)

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways or modules. Reactions are treated as "sets." Custom addition or removal of entities not implemented yet. Weighted enrichment against pathways is slow due to large sizes; enrich_against for this is set to "module" as default. Certain non-meaningful pathways such as k01100 "Metabolic Pathways" are removed from enrichment.

100%|██████████████████████████████████████████████████| 26/26 [00:00<00:00, 163.11it/s]

Analysis run on 20 entities from 27 out of 28 input genes

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,"Pyruvate oxidation, pyruvate => acetyl-CoA",8.290478e-12,6,6,"[K00161, K00161, K00161, K00169, K00382, K00627]",M00307
1,"Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate",5.203119e-07,5,15,"[K00134, K00150, K00844, K00850, K00873]",M00001
2,"Glycolysis, core module involving three-carbon compounds",4.399695e-05,3,8,"[K00134, K00150, K00873]",M00002

Input: kegg orthologs

Maps to: reactions

enriches: reactions against modules


default: displays the reactions found in the pathways

In [5]:
enrich.enrich_wrapper('kegg_test_ko.csv','ko',method='set',fpath = '../test_data/processed/', kegg = True, display_input = True)

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways or modules. Reactions are treated as "sets." Custom addition or removal of entities not implemented yet. Weighted enrichment against pathways is slow due to large sizes; enrich_against for this is set to "module" as default. Certain non-meaningful pathways such as k01100 "Metabolic Pathways" are removed from enrichment.

100%|████████████████████████████████████████████████| 26/26 [00:00<00:00, 13292.53it/s]

Analysis run on 20 entities from 27 out of 28 input genes

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,"Pyruvate oxidation, pyruvate => acetyl-CoA",1.345849e-12,6,6,"[K00161, K00161, K00161, K00169, K00382, K00627]",M00307
1,"Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate",4.133213e-07,5,15,"[K00134, K00150, K00844, K00850, K00873]",M00001
2,"Glycolysis, core module involving three-carbon compounds",8.071106e-05,3,8,"[K00134, K00150, K00873]",M00002

Input: kegg orthologs

Maps to: reactions

enriches: reactions against modules

default: displays the reactions found in the pathways

In [6]:
enrich.enrich_wrapper('kegg_test_ko.csv','ko',method='set',fpath = '../test_data/processed/', kegg = True, display_input = False, enrich_against = 'pathway')

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways or modules. Reactions are treated as "sets." Custom addition or removal of entities not implemented yet. Weighted enrichment against pathways is slow due to large sizes; enrich_against for this is set to "module" as default. Certain non-meaningful pathways such as k01100 "Metabolic Pathways" are removed from enrichment.

100%|████████████████████████████████████████████████| 48/48 [00:00<00:00, 14368.16it/s]

Analysis run on 79 entities from 27 out of 28 input genes

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,Glycolysis / Gluconeogenesis,9.320789e-19,18,53,"[R00754, R00746, R00703, R05198, R00710, R01058, R01061, R00711, R01063, R00014, R03270, R01196,...",ko00010
1,Pyruvate metabolism,1.703289e-10,13,65,"[R00754, R00746, R00703, R05198, R00710, R00711, R00014, R03270, R01196, R07618, R02569, R00200,...",ko00620
2,Chloroalkane and chloroalkene degradation,6.229512e-06,6,25,"[R05233, R05234, R05285, R05237, R05238, R05286]",ko00625
3,Citrate cycle (TCA cycle),1.264370e-05,6,28,"[R00014, R03270, R01196, R01197, R07618, R02569]",ko00020
4,Carbon metabolism,1.224404e-04,13,202,"[R06983, R01058, R01061, R01063, R00209, R01196, R01197, R01221, R08549, R01786, R00756, R04779,...",ko01200
5,Drug metabolism - cytochrome P450,3.802876e-04,3,8,"[R08281, R08306, R08310]",ko00982
6,"Valine, leucine and isoleucine degradation",1.533085e-03,5,44,"[R03869, R07160, R08566, R08567, R07618]",ko00280
7,Galactose metabolism,2.273745e-03,5,48,"[R01786, R03236, R03237, R03238, R03239]",ko00052

Input: EC numbers (second argument should be 'enzyme')
Maps to: reactions
enriches: reactions against pathways

default: displays the reactions found in the pathways

In [7]:
 enrich.enrich_wrapper('kegg_test_ec.csv','enzyme',method='set',fpath = '../test_data/processed/', kegg = True, enrich_against = 'pathway')

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways or modules. Reactions are treated as "sets." Custom addition or removal of entities not implemented yet. Weighted enrichment against pathways is slow due to large sizes; enrich_against for this is set to "module" as default. Certain non-meaningful pathways such as k01100 "Metabolic Pathways" are removed from enrichment.

100%|█████████████████████████████████████████████████| 27/27 [00:00<00:00, 6598.28it/s]

Analysis run on 41 entities from 13 out of 14 input genes

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,Glycolysis / Gluconeogenesis,5.630106e-21,16,53,"[R00959, R02738, R01600, R01786, R02187, R02189, R09085, R09086, R02739, R02740, R03321, R04780,...",ko00010
1,Pentose phosphate pathway,7.306845e-07,7,53,"[R01057, R02739, R02740, R04780, R04779, R09084, R02073]",ko00030
2,Microbial metabolism in diverse environments,5.967443e-06,23,942,"[R00959, R01600, R01786, R02187, R02189, R09085, R09086, R02739, R02740, R03321, R00762, R01845,...",ko01120
3,Galactose metabolism,6.863091e-06,6,48,"[R00959, R01786, R03236, R03237, R03238, R03239]",ko00052
4,Carbon metabolism,2.329022e-05,10,202,"[R01786, R02189, R09085, R02740, R00762, R01845, R04780, R00756, R04779, R09084]",ko01200
5,Amino sugar and nucleotide sugar metabolism,2.802148e-05,8,125,"[R00959, R02738, R01326, R01786, R01961, R03920, R02189, R02740]",ko00520
6,Fructose and mannose metabolism,4.841043e-04,5,66,"[R00867, R01326, R04780, R04779, R02073]",ko00051
7,Biosynthesis of nucleotide sugars,1.675469e-03,7,175,"[R00959, R01326, R01786, R01961, R03920, R02189, R02740]",ko01250

**Weighted Enrichment**

EC numbers against modules

In [10]:
 enrich.enrich_wrapper('kegg_test_ec.csv','enzyme',method='ncHGT',fpath = '../test_data/processed/', kegg = True, enrich_against = 'module')

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways or modules. Reactions are treated as "sets." Custom addition or removal of entities not implemented yet. Weighted enrichment against pathways is slow due to large sizes; enrich_against for this is set to "module" as default. Certain non-meaningful pathways such as k01100 "Metabolic Pathways" are removed from enrichment.

100%|██████████████████████████████████████████████████| 13/13 [00:00<00:00, 273.57it/s]

 not found in dictionary
 not found in dictionary

Analysis run on 15 entities from 13 out of 14 input genes

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,"Nucleotide sugar biosynthesis, glucose => UDP-glucose",0.000000e+00,3,4,"[R00959, R01786, R02189]",M00549
1,"Reductive pentose phosphate cycle, glyceraldehyde-3P => ribulose-5P",0.000000e+00,2,7,"[R00762, R01845]",M00167
2,"Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate",2.084022e-10,6,15,"[R01786, R02189, R09085, R02740, R04779, R09084]",M00001
3,"UDP-N-acetyl-D-glucosamine biosynthesis, eukaryotes, glucose => UDP-GlcNAc",6.299089e-04,2,6,"[R01786, R02740]",M00892
4,"UDP-N-acetyl-D-glucosamine biosynthesis, prokaryotes, glucose => UDP-GlcNAc",6.299089e-04,2,6,"[R01786, R02740]",M00909
5,"Formaldehyde assimilation, ribulose monophosphate pathway",6.627385e-04,2,7,"[R00756, R04779]",M00345

***I need to follow up and see if the 0.00e+00 is an underflow error or something serious.***

Input: EC

Maps to: reactions

enriches: reactions against pathways

display_input = True -> instead of displaying the reactions found in the pathways, displays the ECs instead

In [8]:
enrich.enrich_wrapper('kegg_test_ec.csv','enzyme',method='set',fpath = '../test_data/processed/', kegg = True, display_input = True, enrich_against = 'pathway')

kegg functionality: map kegg orthologs or ECs to reactions and enrich reactions against pathways or modules. Reactions are treated as "sets." Custom addition or removal of entities not implemented yet. Weighted enrichment against pathways is slow due to large sizes; enrich_against for this is set to "module" as default. Certain non-meaningful pathways such as k01100 "Metabolic Pathways" are removed from enrichment.

100%|████████████████████████████████████████████████| 27/27 [00:00<00:00, 10266.18it/s]

Analysis run on 41 entities from 13 out of 14 input genes

,title,pval (uncorrected),# entities in list,#entities in model,shared entities in gocam,url
0,Glycolysis / Gluconeogenesis,5.630106e-21,16,53,"[5.4.2.2, 2.7.1.199, 2.7.1.1, 2.7.1.1, 2.7.1.63, 2.7.1.63, 2.7.1.147, 2.7.1.147, 5.3.1.9, 5.3.1....",ko00010
1,Pentose phosphate pathway,7.306845e-07,7,53,"[5.4.2.2, 5.3.1.9, 5.3.1.9, 3.1.3.11, 2.7.1.11, 2.7.1.146, 2.7.1.90]",ko00030
2,Microbial metabolism in diverse environments,5.967443e-06,23,942,"[5.4.2.2, 2.7.1.1, 2.7.1.1, 2.7.1.63, 2.7.1.63, 2.7.1.147, 2.7.1.147, 5.3.1.9, 5.3.1.9, 5.3.1.9,...",ko01120
3,Galactose metabolism,6.863091e-06,6,48,"[5.4.2.2, 2.7.1.1, 2.7.1.11, 2.7.1.11, 2.7.1.11, 2.7.1.11]",ko00052
4,Carbon metabolism,2.329022e-05,10,202,"[2.7.1.1, 2.7.1.63, 2.7.1.147, 5.3.1.9, 3.1.3.11, 3.1.3.11, 3.1.3.11, 2.7.1.11, 2.7.1.11, 2.7.1....",ko01200
5,Amino sugar and nucleotide sugar metabolism,2.802148e-05,8,125,"[5.4.2.2, 2.7.1.199, 2.7.1.1, 2.7.1.1, 2.7.1.1, 2.7.1.1, 2.7.1.63, 5.3.1.9]",ko00520
6,Fructose and mannose metabolism,4.841043e-04,5,66,"[2.7.1.1, 2.7.1.1, 3.1.3.11, 2.7.1.11, 2.7.1.90]",ko00051
7,Biosynthesis of nucleotide sugars,1.675469e-03,7,175,"[5.4.2.2, 2.7.1.1, 2.7.1.1, 2.7.1.1, 2.7.1.1, 2.7.1.63, 5.3.1.9]",ko01250